services:
  - type: web
    name: company-intel-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:server
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.2
